baseURL: voltwalt.dev
title: VoltWalt
keywords: VoltWalt
description: VoltWalt
paginate: 10
hasCJKLanguage: true
languageCode: 'en-us'
theme: # "hugo-theme-onelou"
params:
  opengraph:
    github: 'https://github.com/VoltWalt'
    twitter: 'https://twitter.com/Moeay0'
  footer:
    hidePowered: false # Powered by Hugo & theme OneLou
    beian: # ICP备案号
    since: 2022
    copyright: XXX
  prefix:
    h2: "※ "
    h3: "✧ "
